name: Build and Deploy Dashboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Refresh datasets
        run: npm run daily
        env:
          ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
          ARBITRUM_RPC_FALLBACKS: ${{ secrets.ARBITRUM_RPC_FALLBACKS }}
          INFURA_ARBITRUM_RPC: ${{ secrets.INFURA_ARBITRUM_RPC }}
          INFURA_ARBITRUM_RPC_FALLBACKS: ${{ secrets.INFURA_ARBITRUM_RPC_FALLBACKS }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
          NO_PROXY: ${{ secrets.NO_PROXY }}
          TOKEN_PRICE_START_DATE: ${{ secrets.TOKEN_PRICE_START_DATE }}
      - name: Build static dashboard
        run: npm run build
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Upload dashboard artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
